version: "3.6"
services:

  imixs-db:
    image: postgres:13.11
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
    volumes: 
      - dbdata:/var/lib/postgresql/data
  
  imixs-app:
    image: imixs/imixs-process-manager:latest
    environment:
      TZ: "CET" 
      LANG: "en_US.UTF-8"  
      #JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixs-db/workflow-db"
      METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    # volumes:
    #   - ./docker/deployments:/opt/jboss/wildfly/standalone/deployments/

  # Imixs Micro Engine
  workstation-1:
    image: imixs/imixs-micro-engine:latest
    ports:
      - "8081:8080"      
    volumes:
      - ./workflow/micro/:/bpmn/
  workstation-2:
    image: imixs/imixs-micro-engine:latest
    ports:
      - "8082:8080"     
  workstation-3:
    image: imixs/imixs-micro-engine:latest
    ports:
      - "8083:8080"     

  # Imixs Admin Client
  # imixsadmin:
  #   image: imixs/imixs-admin:latest
  #   ports:
  #     - "8888:8080"      
      
volumes:
  dbdata:   